# 사이트의 기본 정보
title: Jjalkyue_TIL                # 사이트 제목
description: 공부한내용 열심히 적어보자  # 사이트 설명
baseurl: "/Jjalkyu.github.io"         # 레포지토리 이름이나 하위 URL 경로
url: "https://jjalkyu.github.io/"  # GitHub Pages의 기본 도메인

# URL 구조 설정
permalink: /:categories/:year/:month/:day/:title/ # URL 패턴
# 마크다운으로 변환
markdown: kramdown
