name: Update README with Date

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"  # 매일 자정에 실행

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Update README.md with date
        run: |
          python -c 'from datetime import datetime; print(f"업데이트 날짜: {datetime.now().strftime("%Y년 %m월 %d일")}")' > temp_date.txt
          sed -i "s|업데이트 날짜: .*|$(cat temp_date.txt)|" README.md

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "자동 날짜 업데이트"
          git push
