name: Update Today's Date in README

on:
  push:
    branches:
      - main  # main 브랜치에서 푸시될 때 실행
  schedule:
    - cron: "0 0 * * *"  # 매일 자정(UTC) 실행

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      # 1. 레포지토리 클론
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2. README.md에서 오늘의 날짜 업데이트
      - name: Update README.md with today's date
        run: |
          TODAY=$(date +"%Y년 %m월 %d일")
          sed -i "s|<span style=\"color:gray; opacity:0.7;\">.*</span>|<span style=\"color:gray; opacity:0.7;\">오늘의 날짜: ${TODAY}</span>|" README.md

      # 3. 변경 사항 커밋 및 푸시
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "자동으로 오늘의 날짜 업데이트"
          git push
